services:
  - type: web
    name: habbits-tracker
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: DATABASE_ID
        sync: false
